### ISSUE TITLE
Total points only counted if at least one score is inserted

### ISSUE THREAD

**Issue by luttje** [curio-team/smartpoints2#30]
This bug feels like it could be a feature. The total points (underlined in green below) are only counted if  at least one score is entered into the column.

![image](https://github.com/curio-team/smartpoints2/assets/2738114/f77d5b95-c8df-4282-b406-3e65339a2fbd)

_e.g: You can increase the total points to 12 by putting any score for any student in the FESD column_

**Comment by bartjroos** [comment]
This **is** actually a feature
