### ISSUE TITLE
Composer update sdclient zodat namen gesynct kunnen worden

### ISSUE THREAD

**Issue by StevenVanRosendaal** [curio-team/smartpoints2#36]
We kwamen er achter dat de namen van studenten/docenten bij de eerste login gezet worden, maar als de naam van de student verandert (trouwen / andere redenen) dan wordt deze nooit meer opnieuw gesynchroniseerd. Dit is geüpdate in de laatste versie van de SDClient.

**Comment by luttje** [comment]
Waarschijnlijk heb ik morgen wel tijd om de sdclient package te updaten, samen met andere packages die security updates hebben (https://github.com/curio-team/smartpoints2/security/dependabot)
